# Generated by Django 5.2 on 2025-05-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('Yüksek', 'Yüksek'), ('Orta', 'Orta'), ('Düşük', 'Düşük')], default='Orta', max_length=10)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
